### ISSUE TITLE
Visibility of note, caution... boxes

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#100]
It looks like the accessibility/visibility of the Sphinx caution and note boxes has been reduced. For example:

![image](https://user-images.githubusercontent.com/37798125/185374383-ec996bb9-742e-4599-83ee-13367ca6d385.png)

I would either change the color or make it darker. Plus the "info" symbol is barely identifiable. 

Pinging @jorgepiloto for discussion and @Revathyvenugopal162 for implementation

**Comment by jorgepiloto** [comment]
Closing this issue as it got solved in #116.
