### ISSUE TITLE
Problem with deprecated and versionadded notes color mode

### ISSUE THREAD

**Issue by PProfizi** [ansys/ansys-sphinx-theme#121]
Hi there! 
I was testing the different sphinx notes available to put in dosctrings, and I wanted to check `.. deprecated::` and `.. versionadded::` (see [here](https://github.com/pyansys/pydpf-core/blob/0249a141630b772b1fb1dd469015b7437bb7a53f/ansys/dpf/core/string_field.py#L24-L57)).

I found out that the general color theme is problematic as my local computer is in dark mode, giving this in doc dark mode:
![image](https://user-images.githubusercontent.com/100710998/191966891-769f195e-c37d-4ca8-a3f0-3502a8caedc4.png)

Yet not rendering those two notes properly when in light or auto mode:
![image](https://user-images.githubusercontent.com/100710998/191967021-1c7d0ad9-985e-46a3-ae51-3b173eaddb2d.png)
![image](https://user-images.githubusercontent.com/100710998/191967068-fed2d9a3-8486-47f9-b1fb-1cde696d7217.png)

I think those two notes always use my local computer's dark mode despite the doc's mode.
The text is there, it is just not visible because the documentation's color theme makes it black, while the back of the note is not made white and seems to bypass the doc's color mode.
The problem might come from ansys-sphinx-theme, or it might come from our conf.py at PyDPF-Core.
What do you think?

**Comment by germa89** [comment]
Same here with `Deprecated` (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) directive in Sphinx:

![image](https://user-images.githubusercontent.com/28149841/209646086-9934a345-a05a-4946-aab4-42bdb918e58d.png)


It does work in dark mode.
![image](https://user-images.githubusercontent.com/28149841/209646019-a85260c6-9cf6-413d-b86d-d11f51bee7bb.png)
