### ISSUE TITLE
Problem with ansys-sphinx-theme on automated API  width

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#131]
See link: https://dev.mechanical.docs.pyansys.com/api/_autosummary/ansys.mechanical.core.pool.LocalMechanicalPool.html

Seems to me like something is wrong here with the theme...

![image](https://user-images.githubusercontent.com/37798125/194097916-175f08a7-6f56-430d-afb5-3212245b0271.png)

**Comment by MaxJPRey** [comment]
@RobPasMue Let's check that #130 fix it everywhere.
