### ISSUE TITLE
Problems still appear on menus

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#132]
As reported from https://dev.mechanical.docs.pyansys.com/api/_autosummary/ansys.mechanical.core.pool.LocalMechanicalPool.html

![image](https://user-images.githubusercontent.com/37798125/194262385-78068f5f-d489-4963-81f8-b0020a845354.png)

Problems with #130 (related to #131) have been solved... but new issues have arisen. We should fix them.

Issues have been highlighted in red.

**Comment by Revathyvenugopal162** [comment]
Closing this issue, as resolved by ansys-sphinx-theme 0.7.0.https://dev.mechanical.docs.pyansys.com/api/_autosummary/ansys.mechanical.core.pool.LocalMechanicalPool.html
