### ISSUE TITLE
Ansys Sphinx theme documentation gives Error 404

### ISSUE THREAD

**Issue by PProfizi** [ansys/ansys-sphinx-theme#144]
[Ansys Sphinx theme documentation](https://sphinxdocs.pyansys.com/) as seen in https://sphinxdocs.ansys.com/#introduction currently first blocks as "not secure" and finally ends-up as "404 There isn't a GitHub Pages site here".

**Comment by RobPasMue** [comment]
Good catch @PProfizi! The issue is with the domain.. That link is pointing to ``pyansys.com`` instead of ``ansys.com``. Let me quickly fix it.
