### ISSUE TITLE
Inherit theme from latest pydata-sphinx-theme

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#156]
The ansys-sphinx-theme is now using pydata-sphinx-theme-0.9.0, so we are not able to make use of the latest features like, announcements, dropdown customization, and search bar. In addition, the HTML pages that control the layout for the navigation bat do not longer exist in the `pydata-sphinx-theme===0.9.0`, meaning that we lost control over this component of the page unless we update.

Below are the list of issues need to be addressed to update our theme:

- [x] #183

- [x] #184

- [x] #185

- [x] #189

Since we migrated everything to `pyproject.toml`, now dependabot will update to newer versions of `pydata-sphinx-theme`. Previous `examples.rst` will allow us to manually check if the style was kept by cloning locally the pull-request. We also need to explore #41, but let us focus first on this issue.

**Comment by jorgepiloto** [comment]
I just edited the description a bit more to explain to other team members.

**Comment by RobPasMue** [comment]
Thanks @jorgepiloto, much appreciated. Let us know if you need any help with this.

**Comment by jorgepiloto** [comment]
@Revathyvenugopal162, would you mind to address the `examples.rst` file and the style tasks? I know you are way more experienced than me when working with those. If so, I can address the HTML layout files task.
