### ISSUE TITLE
No changelog in the GitHub Releases

### ISSUE THREAD

**Issue by PProfizi** [ansys/ansys-sphinx-theme#168]
Hi!

Quick question about the releases of ansys-sphinx-theme.
For the last releases there has been no changelog or release description, so when dependabot opens a PR to bump the version of this dependency in my project, I cannot read what's changed with new new version as I usually can.
Is there a reason?

**Comment by Revathyvenugopal162** [comment]
@PProfizi As most of the changes were from the patch release, The release note was not generated automatically, updated the release note and  now you will be able to see it.

**Comment by Revathyvenugopal162** [comment]
closing as fixed.
