### ISSUE TITLE
Outdated ``pydata-sphinx-theme``

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#172]
Is there any reason for pining ``pydata-sphinx-theme``??

https://github.com/ansys/ansys-sphinx-theme/blob/fd9122541a9fc9f339058a72343955549d755ae9/pyproject.toml#L29

they are already at 0.12 version:

https://github.com/pydata/pydata-sphinx-theme

**Comment by germa89** [comment]
Ohh... I see....

https://github.com/ansys/ansys-sphinx-theme/pull/155

**Comment by RobPasMue** [comment]
Yep, that may take some time to resolve... Since there is an ongoing PR already, I'd propose to close this issue.

**Comment by RobPasMue** [comment]
Issue tracking down this problem: #156
PR tracking down this problem: #155
