### ISSUE TITLE
Dropdown menu should take you to the equivalent vXXX page

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#175]
### 📝 Description of the feature

I think it will be nice if the dropdown takes you to the equivalent page in the previous/newer version.

For example if we are in `v2`` of ``examples.html`` and we select version ``v1``, it should take you to the version 1 of  ``examples.html``, not back to main. So we can compare changes in the API easier.

I think it should not be difficult to implement. I understand that a 404 error should be shown if that specific page didn't exist in the newly selected version.

_Originally posted by @germa89 in https://github.com/pyansys/actions/issues/122_

**Comment by Revathyvenugopal162** [comment]
closing as solved this issue with https://github.com/pyansys/actions/issues/151 and upgrade of pydata-sphinx-theme. Implementation in https://sphinxdocs.ansys.com/dev/user_guide/index.html

**Comment by germa89** [comment]
Thank you guys!! :D
