### ISSUE TITLE
Create a `examples.rst` and link this file within the `index.rst`. 

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#184]
Create a examples.rst and link this file within the index.rst. The examples.rst must contain a collection of directives coming from the Sphinx extensions that we support across our projects. This will allows us to properly fix the style for those.

**Comment by jorgepiloto** [comment]
Ideally, we should try to automate this as much as possible. If we could download and filter the RST files from the extension libraries we want to support, this would be a relief in our side.

**Comment by Revathyvenugopal162** [comment]
Done in #191
