### ISSUE TITLE
Enum values are not being documented with autosummary

### ISSUE THREAD

**Issue by greschd** [ansys/ansys-sphinx-theme#186]
When documenting an `Enum` with ``autosummary`` using the ``ansys-sphinx-theme``, the enum values are not documented.

Minimal reproducing repository: https://github.com/greschd/sphinx-theme-enum-test
Screenshot:

![image](https://user-images.githubusercontent.com/5692808/214346510-8aac4a4b-f1df-47fe-8211-3d03b79d471d.png)

Switching the ``html_theme`` to ``alabaster`` fixes the problem:

![image](https://user-images.githubusercontent.com/5692808/214346677-94de97e2-823f-4a35-981b-b3c92d643756.png)

**Comment by greschd** [comment]
Maybe related to #77 ?

**Comment by greschd** [comment]
Another oddity is that the enum values _are_ documented if their names are all-lowercase.

**Comment by greschd** [comment]
It appears the `class.rst` explicitly skips these attributes: https://github.com/ansys/ansys-sphinx-theme/blame/main/src/ansys_sphinx_theme/_templates/autosummary/class.rst#L28

I wonder what's the reason for this. @Revathyvenugopal162, @akaszynski, @jorgepiloto, does one of you know?

**Comment by jorgepiloto** [comment]
Thanks for opening this issue, Dominik. I know some of our libraries are documenting enumerations and take advantage of an Sphinx extension. Let me find it.

**Comment by greschd** [comment]
Hi @jorgepiloto, we got around this by including a custom `class.rst` which removes the following if-statement [1]:

https://github.com/ansys/ansys-sphinx-theme/blob/4f3629c13c8068d5bc9979479e8dd0406f376c1f/src/pyansys_sphinx_theme/_templates/autosummary/class.rst#L29

The effect is that all attributes which start with an uppercase letter are ignored. However, I don't know why this was included in the first place.

I'm also not sure if the issue still exists with the current re-work going on to base the theme on a newer pydata-theme.

[1] link in my comment above is broken, here's the permalink

**Comment by greschd** [comment]
All that is to say: I don't think we need an extension for enums, the pydata theme already supports this. But our theme (intentionally?) breaks it, which we should either fix or make configurable.

**Comment by jorgepiloto** [comment]
I was able to reproduce all the steps you describe in this issue, @greschd. You are right about the conditional. I am not sure which is the purpose of ignoring attributes starting with uppercase but let's remove this condition from our template.

All attributes should be documented by default, from my point of view.
