### ISSUE TITLE
Problems with menu button on light mode

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#188]
It looks like despite of the theme version we still have problems with the menu button

![image](https://user-images.githubusercontent.com/37798125/214617979-8ea1d522-74f8-493e-9bf0-8d032a5bf128.png)

Could you please look into it @Revathyvenugopal162? Maybe it's already part of #185 but I couldn't really tell.

**Comment by MaxJPRey** [comment]
I have a different issue but related to the light theme and menu button too.
I don't see the different versions unless I hover over the tab.
Adding it here:

![image](https://user-images.githubusercontent.com/87315832/214803819-7ca27077-adf4-4d00-8926-6651d1fe3b90.png)

**Comment by Revathyvenugopal162** [comment]
Closing as addressed both issues in https://github.com/ansys/ansys-sphinx-theme/pull/187
