### ISSUE TITLE
Limit major sphinx version to Sphinx<6

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#192]
🐞 **Problem**
The latest sphinx version introduces some issues that we still need to address. For the moment, I would suggest to limit the major version for Sphin for the moment.

This will prevent from users for having a broken logo or version switcher.

**Comment by jorgepiloto** [comment]
Pinging here @Revathyvenugopal162.

**Comment by Revathyvenugopal162** [comment]
Thanks for opening the issue @jorgepiloto , I agree, we can limit the sphinx <6  for all the libs.

**Comment by jorgepiloto** [comment]
Also, let's do the patch release on Monday to avoid issues caused during the weekend.

**Comment by Revathyvenugopal162** [comment]
Sure. I will modify both by this afternoon., and will go for patch on monday morning.

**Comment by Revathyvenugopal162** [comment]
Closing as addressed this in #193
