### ISSUE TITLE
``get_version_match()`` should accept the semver regex

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#197]
Following PEP 440, we should accept the following semver regex for identifying major minor

https://peps.python.org/pep-0440/#public-version-identifiers

Problems appeared in https://github.com/pyansys/pyprimemesh/pull/373 since they name their versions as X.Y.Z.devN which means that there are 4 elements in dev releases. Honestly, we should just implement the method like this (quick fix):

```py
def get_version_match(semver: str) -> str:
    """..."""
    if "dev" in semver:
        return "dev"
    major, minor, _ = semver.split(".")
    return ".".join([major, minor])
```

**Comment by RobPasMue** [comment]
Pinging @ninad-kamat for visibility

Pinging @jorgepiloto and @Revathyvenugopal162 for debate.

**Comment by ninad-kamat** [comment]
I would probably suggest a minor modification.
```python
def get_version_match(semver: str) -> str:
    if "dev" in semver:
        return "dev"
    major, minor, _ = semver.split(".", 3)
    return ".".join([major, minor])
```
This can account for any `rc` or other post release tags that may be added to the version.

**Comment by RobPasMue** [comment]
PR in place and about to be merged. This will be available in the next ``ansys-sphinx-theme`` release @ninad-kamat
