### ISSUE TITLE
Can not build documentation without using the version switcher

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#213]
🐞 **Problem**
It looks like there is a configuration inherited at some point that is forcing the theme to use the version switcher. We need to identify where this is happening an offer the possibility to ignore multi-version.

Original issue is this one: https://github.com/pyansys/dev-guide/pull/262

**Comment by Revathyvenugopal162** [comment]
Thanks for opening this issue @jorgepiloto . Closing this as this has been solved #214
