### ISSUE TITLE
Multiple links in API reference TOC Tree appear on same line

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/ansys-sphinx-theme#233]
The HTML docs generated for ansys-openapi-common show this in the API reference TOC tree (0.9.6 and 0.9.5):

![image](https://user-images.githubusercontent.com/6451062/230947799-fb9aaa3c-72bb-4fa9-9e6a-41bca8c4d1a7.png)

Compared to the current output in the published docs (package version 0.7.1)

![image](https://user-images.githubusercontent.com/6451062/230947899-9a6ce43d-b9ea-47b9-9bb3-7dc2ab4f997d.png)

This then produces a strange layout when clicking one of the links:

![image](https://user-images.githubusercontent.com/6451062/230949873-d96e6881-5f74-44f3-8940-dcf2a4b55281.png)

We do not have multi-version docs set up yet for openapi-common, so see the artifacts generated by the CI in this PR https://github.com/pyansys/openapi-common/pull/338 for the actual generated HTML. It looks like the change occurred somewhere between 0.7.1 and 0.9.5, I just only noticed when checking the 0.9.5 to 0.9.6 PR.

**Comment by Revathyvenugopal162** [comment]
@Andy-Grigg it is because of the sidebar_nav_bar.html present in the templates, which overrides the existing sidebar settings by pydata and ansys-sphinx-theme. i removed the html files. and hopefully it will solve the issue.

**Comment by Andy-Grigg** [comment]
Thanks @Revathyvenugopal162 , your commit has indeed solved this issue. See https://github.com/pyansys/openapi-common/pull/338/commits/eb857e49857bcc738657a687c612b30b0da8af34 for the commit.

Closing this issue.
