### ISSUE TITLE
Visibility of "Hide search matches" button

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#253]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

#### Currently - light mode - not overing
<img width="411" alt="image" src="https://github.com/ansys/ansys-sphinx-theme/assets/28149841/eb4a954d-489d-4b9b-b79b-f6d3e41d3d3c">

#### Currently - light mode - overing
<img width="368" alt="Screenshot 2023-06-12 at 18 06 09" src="https://github.com/ansys/ansys-sphinx-theme/assets/28149841/56a63656-3c13-4272-918d-22d610973aa9">

### 📝 Steps to reproduce

Visit:

https://mapdl.docs.pyansys.com/version/stable/mapdl_commands/post1/_autosummary/ansys.mapdl.core.Mapdl.set.html#set

**Comment by greschd** [comment]
Ha, I was about to post the same!

> ### 📝 Steps to reproduce
> 
> Visit:
> 
> https://mapdl.docs.pyansys.com/version/stable/mapdl_commands/post1/_autosummary/ansys.mapdl.core.Mapdl.set.html#set

At least for me simply going to that page doesn't show the button. I can reproduce it with

- search for a term (e.g. "test")
- go to one of the suggested locations
