### ISSUE TITLE
Make card dimensions adaptable to all devices  

### ISSUE THREAD

**Issue by klmcadams** [ansys/ansys-sphinx-theme#256]
### Description of the modifications

The cards on the main pyansys page (https://docs.pyansys.com/version/stable/) are squished when viewed on a mobile phone (see attached). We could make it so it only shows two cards per row, and/or adjust the css to be flexible and adapt to the size of the device being used. 

![image](https://github.com/ansys/ansys-sphinx-theme/assets/58492561/062f5d5a-4218-4a88-87ef-71e47dba052d)

### Useful links and references

https://docs.pyansys.com/version/stable/

**Comment by Revathyvenugopal162** [comment]
Thanks for opening issue @klmcadams , @AlejandroFernandezLuces already mentioned this issue, and i am working on this.

**Comment by MaxJPRey** [comment]
@Revathyvenugopal162 When it is done, might be worth it to do some additional testing about other contents and pages. For instance, make sure that the dev guide is rendering properly and we did not downgraded any UI/UX part.

**Comment by RobPasMue** [comment]
Testing on different devices might be difficult in terms of CI/CD. But we should explore this. I'm no expert on CSS but happy to learn

**Comment by Revathyvenugopal162** [comment]
It is already doing with pydata, we do have an open issue to adapt tests, we are adding this with different devices when we are modifying with pydata, but for sphinx cards, they dont have customization, so we just have to adapt their tests only for the sphinx design, until they have some from their side.

**Comment by Revathyvenugopal162** [comment]
Thank you for opening the issue, fixed with v1.0.5 and closing the issue.
