### ISSUE TITLE
Switcher not working on phone version

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#302]
Looks like the switcher is not rendering properly on phones... Happens in PyMAPDL, PyAnsys Geometry...

See behavior
![MicrosoftTeams-image](https://github.com/ansys/ansys-sphinx-theme/assets/37798125/342a8f2d-85a3-484e-8e1e-213979ad14f0)

**Comment by Revathyvenugopal162** [comment]
closing as this issue solved.
