### ISSUE TITLE
Level 2 headers not always expanded below "On this page" 

### ISSUE THREAD

**Issue by ansbmartin** [ansys/ansys-sphinx-theme#314]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I have a RST page with two levels of headers:

```
Title1
  Subtitle 11
  Subtitle 12
  Subtitle 13
Title 2
  Subtitle 21
  Subtitle 22
  Subtitle 23
Title 3
  Subtitle 31
  Subtitle 32
  Subtitle 33
Title 4
  Subtitle 41
  Subtitle 42
  Subtitle 43
```

- open the the HTML page
- resize the browser window height to display
   ```
   Title1
     Subtitle 11
     Subtitle 12
     Subtitle 13
   Title 2
     Subtitle 21
     Subtitle 22
     Subtitle 23
   Title 3
     Subtitle 31
   ```
On the HTML page:
- in "On this page", click on "Title 4"  => "Title 3" is selected and expanded whereas I would expect "Title *4*" to be selected and expanded
- in "On this page", click on "Title 2" => "Title 1" is selected and expanded whereas I would expect "Title *2*" to be selected and expanded

[ansys-theme-bug-onthispage.zip](https://github.com/ansys/ansys-sphinx-theme/files/13039677/ansys-theme-bug-onthispage.zip)

### 📝 Steps to reproduce

``` powershell
python -m venv .venv
.venv\Scripts\Activate.ps1
python -m pip install sphinx ansys-sphinx-theme
sphinx-build -M html . _build
```
Then open `_build/html/page1.html` (tested with Edge 117.0.2045.60 on Windows 11)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ansys-sphinx-theme            0.12.3

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
accessible-pygments==0.0.4
alabaster==0.7.13
ansys-sphinx-theme==0.12.3
Babel==2.13.0
beautifulsoup4==4.12.2
certifi==2023.7.22
charset-normalizer==3.3.0
colorama==0.4.6
docutils==0.20.1
idna==3.4
imagesize==1.4.1
importlib-metadata==6.8.0
Jinja2==3.1.2
MarkupSafe==2.1.3
packaging==23.2
pydata-sphinx-theme==0.14.1
Pygments==2.16.1
requests==2.31.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
typing_extensions==4.8.0
urllib3==2.0.7
zipp==3.17.0
```

**Comment by Revathyvenugopal162** [comment]
Thank you for opening the issue, the issue is fixed and theme reformatted with v1.0.5 https://github.com/ansys/ansys-sphinx-theme/releases
