### ISSUE TITLE
Procedures with second-level steps aren't formatted correctly. 

### ISSUE THREAD

**Issue by PipKat** [ansys/ansys-sphinx-theme#316]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

See the following topic, which has second -level steps. The second-level step should align with the text of the first step and use alpha characters. Currently, they are indented too far to the right and use numbers. For more information, see the issue originally opened in the PyAnsys Writer's Guide: https://github.com/ansys-internal/pyansys-writer-guide/issues/35. 

https://urban-succotash-l5z5z13.pages.github.io/getting_started/dev_environment.html#install-and-use-the-ansys-python-manager

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
NA
```

**Comment by jorgepiloto** [comment]
Hi @PipKat, this is not an issue on the theme. See this syntax for using alphabetical characters in nested lists:

```rst
- A bullet list

  #. Nested number list.
  #. Nested item 2.

- A bullet list item 2.

  Paragraph 2 of item 2.

  * Nested bullet list.
  * Nested item 2.

    A. Third level staring with 'A'
    #. Third level item B.

  * Nested item 3.
```

I tested previous code ans it is working smoothly. Thus, I am closing this issue.

References: https://labs.bilimedtech.com/workshops/rst/writing-rst-4.html#rst-nested-lists
