### ISSUE TITLE
Frame lines are missing

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/ansys-sphinx-theme#328]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

At the bottom of the Getting Started page some lines of the frame are discontinued.

See:
<img width="918" alt="image" src="https://github.com/ansys/ansys-sphinx-theme/assets/87315832/77b873b8-1e15-4960-92fb-932f79b6d0f0">

### 📝 Steps to reproduce

Navigate to PyAnsys Geometry to see the issue:
https://geometry.docs.pyansys.com/version/stable/getting_started/index.html

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

n/a

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
n/a
```

**Comment by jorgepiloto** [comment]
I can no longer see this issue in docs rendered with 0.15 version. Is this still showing up for you, @MaxJPRey? If not, feel free to close the issue.

**Comment by RobPasMue** [comment]
Yeah I believe this no longer happens.

**Comment by MaxJPRey** [comment]
@jorgepiloto I don't see anymore the issue on my side. Closing the issue.
