### ISSUE TITLE
Incorrect Formatting for Nested Projects

### ISSUE THREAD

**Issue by da1910** [ansys/ansys-sphinx-theme#329]
Projects within the "Shared Components" section have two parent pages, the root pyansys docs, and the Shared Components docs. This is not correctly rendered with theme version 0.12.5 or with 0.12.2:

![image](https://github.com/ansys/ansys-sphinx-theme/assets/12086549/19bbf6dc-f98e-478d-858f-f64ccf3d777a)

Available at https://openapi.docs.pyansys.com/index.html also

I expect the correct delimiter between the first two elements, not a single unspaced slash.

```
html_theme_options = {
    "github_url": "https://github.com/pyansys/openapi-common",
    "show_prev_next": False,
    "show_breadcrumbs": True,
    "additional_breadcrumbs": [
        ("PyAnsys Documentation", "https://docs.pyansys.com"),
        ("Shared Components", "https://shared.docs.pyansys.com")
    ]
}
```

This is the relevant snippet from our conf.py file

**Comment by Revathyvenugopal162** [comment]
Thanks for opening the issue @da1910 , i will look in to it and update the breadcrumbs.
