### ISSUE TITLE
Keyboard strokes cannot be seen properly in dark mode

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#333]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The keyboard strokes cannot be seen properly in dark mode:

https://mapdl.docs.pyansys.com/version/dev/getting_started/codespaces.html#how-to-connect-to-an-already-existing-instance

### 📝 Steps to reproduce

https://mapdl.docs.pyansys.com/version/dev/getting_started/codespaces.html#how-to-connect-to-an-already-existing-instance

**Comment by RobPasMue** [comment]
I wouldn't say properly... they can't be seen at all 😄

**Comment by germa89** [comment]
> I wouldn't say properly... they can't be seen at all 😄

I was trying to be polite xDDD

**Comment by RobPasMue** [comment]
> I was trying to be polite xDDD

Me too
<img src="https://media4.giphy.com/media/osaht29jlIv0CYWsQt/giphy.gif"/>

**Comment by Revathyvenugopal162** [comment]
Closing this issue as this is fixed with version v1.0.5
