### ISSUE TITLE
Consider using the "friendly" pygments style as the default highlighting style

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#340]
🐞 **Problem**

The current syntax highlighting is out of sync with the rest of our theme. It's colors are pallid and not vibrant.

A common theme is the [friendly](https://www.florian-diesch.de/doc/sphinx/themes-and-pygments-styles/sphinxdoc_friendly/index.html) style, by [Pygments](https://pygments.org/). This theme is more shiny and its colors better our corporate theme (from my point of view).

Of course, this is open to discussion. There are plenty of options, see [available Pygment themes](https://pygments.org/styles/).

Sphinx provides the following option for setting a default theme:

```python
pygments_style: str
```

However, it does not seem to work. Maybe, our template CSS takes priority over this option.

Ideally, we should override this by adding the CSS file we agree from [this repo](https://github.com/richleland/pygments-css). License is `UNLICENSE.txt`. Thus, corporte usage is accepted. We can always include a small comment at the top of the style file.

**Comment by greschd** [comment]
As a side note: we need both a _light_ and _dark_ highlighting theme.

**Comment by jorgepiloto** [comment]
I guess we could go with `monokai` in that case for the dark theme. I think it is one of the most popular ones out there.

**Comment by RobPasMue** [comment]
I like monokai 😄 so works for me!
