### ISSUE TITLE
Default Style on Search Box

### ISSUE THREAD

**Issue by da1910** [ansys/ansys-sphinx-theme#360]
![image](https://github.com/ansys/ansys-sphinx-theme/assets/12086549/9d4c28b1-0b1f-430d-9d15-47c1c0f90eaa)
If you run a search in either light or dark mode you get this lovely popup - it's a little odd that it comes up rather than letting you type in the search box on the page.

Additionally you get a nice purple highlight which doesn't match the style anywhere else when you're typing.

I would expect to just have the box in the top corner as the input... Is there some reason we elected to go with the popup?

![image](https://github.com/ansys/ansys-sphinx-theme/assets/12086549/f929f0b8-86a7-400e-b381-c99877643e0b)

**Comment by jorgepiloto** [comment]
That's a good point, @da1910. This default behavior is due to our inheritance from the `pydata-sphinx-theme`. However, I agree about having something similar to https://fastapi.tiangolo.com/.

Pinging here mia-guo-ux to have a better opinion on this.

**Comment by mia-guo-ux** [comment]
I also prefer the search box similar to [https://fastapi.tiangolo.com/]() as it is subtler and more similar to our design style. 
![Search](https://github.com/user-attachments/assets/51eb888c-5d3e-48c0-95bd-e7157c02748b)
