### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#373]
Years have passed and this theme has evolved into a more mature project. New hooks and extensions are available. However, the documentation is dragging behind the development.

We need to ensure the following sections:

```
- Getting started
  - Installation
    - Users
    - Developers

- User guide
  - Basics
  - Extensions
    - Multi-version docs 
    - PyMeilisearch
    - Autoapi
    - Others?

- Examples
- Changelog
```

**Comment by jorgepiloto** [comment]
Note that most of the content is in place. We just need to refactor it.

**Comment by RobPasMue** [comment]
Agreed - this would be great to have!
