### ISSUE TITLE
When clicking on the card, the link does not work

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/ansys-sphinx-theme#392]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Go to this url: https://docs.pyansys.com/
Then click on any card, nothing will happen.
![image](https://github.com/ansys/ansys-sphinx-theme/assets/87315832/68318253-7d38-4948-9f75-dfacf479c422)

We are expecting to be redirected to the proper product documentation.

**Note:** if you switch the version in the top right corner to stable, it works as expected.
The issue also appears for the actions documentation. See https://actions.docs.ansys.com/version/dev/index.html

### 📝 Steps to reproduce

n/a

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
n/a
```

**Comment by RobPasMue** [comment]
We need to get this fixed and released asap

**Comment by jorgepiloto** [comment]
We can not use the `display: none`. This removes the link. Even with that, using `visiblity: hidden` does not work neither... Investigating...
