### ISSUE TITLE
Using PyAnsys logo with transparent background

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#398]
In PyMAPDL we are using a PyAnsys logo with transparent background:

* [dark_mode](https://github.com/ansys/pymapdl/blob/main/doc/source/_static/pyansys-logo-dark_mode.png)

* [light_mode](https://github.com/ansys/pymapdl/blob/main/doc/source/_static/pyansys-logo-light_mode.png)

I strongly believe that the background is not part of the logo, so we should not provide logos with it. 

Hence I would like to propose to use those logos inside ``ansys-sphinx-theme`` so everybody can use them.
This should make the UI/UX integration easier too.

**Comment by greschd** [comment]
> I strongly believe that the background is not part of the logo

I think that's .. only partially true. The brand portal specifies the backgrounds over which the black / white text variants may be used. As such, the no-background variant could be seen as making it easier to misuse the logo.

**Comment by greschd** [comment]
> In PyMAPDL we are using

To be specific, the color `#232323` used in the PyMAPDL header is not one of the Ansys brand colors, and thus does not meet the brand requirements. You could use `#373B37` instead.

**Comment by germa89** [comment]
I guess this conversation is tight to #399. If we go for another theme colours, this conversation will go more relevant/irrelevant... maybe even needed if we do not chose a black/white color for the header.

I would be happy to `#373B37` instead of black.

**Comment by jorgepiloto** [comment]
This has been fixed in version `v1.0`. For Ansys and PyAnsys users, check https://sphinxdocs.ansys.com/version/stable/user-guide/configuration.html#pyansys-and-ansys-logos
