### ISSUE TITLE
Theme colours proposal

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#399]
## Current status

In PyMAPDL docs we have switched away from the default black header (``rgb(0, 0, 0)``) and white background (``rgb(255, 255, 255)``).
Now we use a lighter dark (``rgb(35, 35, 35)``) and a darker white (``rgb(245, 245, 245)``). 

## Proposal

I'm not UX/UI expert, but I believe that we should to run away from strong colours (not black, nor white, or primary colours). As any UX/UI change it is difficult for me to argue why we should do this PR, but on a very simple approach: I just like these palette better than the current one. 🤷🏻‍♂️

## Header comparison

<img width="999" alt="image" src="https://github.com/ansys/ansys-sphinx-theme/assets/28149841/da357de2-7189-460b-bbd4-d285a00f6cc4">
<img width="1024" alt="image" src="https://github.com/ansys/ansys-sphinx-theme/assets/28149841/e7d4bb74-ed8e-449a-8975-f65dc41fb390">

## Background 

<img width="911" alt="image" src="https://github.com/ansys/ansys-sphinx-theme/assets/28149841/3399572d-21ae-43b9-b04c-ef47c70482eb">

## Deployed example

You can check how those colours look in PyMAPDL docs:

https://mapdl.docs.pyansys.com/version/dev/index.html

## Code changes
The code for that change is given in here: 

https://github.com/ansys/pymapdl/blob/de18185752e8e1cfdf9f21f7efd1b2f64f9559df/doc/source/_static/custom.css#L23-L47

Related PR: https://github.com/ansys/pymapdl/pull/2727

Related somehow to: https://github.com/ansys/ansys-sphinx-theme/issues/398

**Note**: Supercool that github renders the color!!

**Comment by RobPasMue** [comment]
Pinging @ansys/developers since this change affects all of us.

While I do agree (personally speaking) with the fact that the colors are more user friendly, I don't think we can do this change as lightly as proposed. Meaning, that our marketing team and UI/UX team would have to approve this change.

Also, if we decide not to change it... I strongly suggest that PyMAPDL aligns with the rest of the colors, mostly because we are all using the same brand styling and it looks very odd that one library goes "solo" in this topic. Navigating through documentation sites should be smooth for users and the theme shouldn't change. As part of the ecosystem, there are certain rules we all have to respect and be aligned with (even though we may have personal preferences).

If we decide to change it, all libraries would have to update their ansys-sphinx-theme versions to the latest one in which this change is implemented.

Nonetheless, this big change requires alignment and agreement from the entire PyAnsys ecosystem since it affects all of us - as well as the teams in charge of branding and accessibility (UI/UX). Pinging as well our @ansys/documentation team since they will have a lot to say for sure.

CC'ing @ansys/pyansys-core for observability and action based on decision

**Comment by Revathyvenugopal162** [comment]
Additionally, you can check the accessibility standards using the guidelines provided here: https://wave.webaim.org/report#/https://sphinxdocs.ansys.com/ and  https://www.w3.org/WAI/standards-guidelines/wcag/. Currently, we are evaluating using white and black backgrounds. If we change the colors, we will need to adjust all the color contrasts accordingly

**Comment by seanpearsonuk** [comment]
I would like to propose:
- **make light mode a true light mode**, which means that the navigation bar is white(ish), not black. Many people detest dark modes in general, so if people are choosing light mode, we should honour that.
- **use shades of grey** instead of pure black-and-white, as already proposed by @germa89. Note also that ansys.com uses a lot of **patterned black rather than solid black** everywhere. But I'm not convinced that we have to change _both_ colours. I think that the black can be toned down but the white can be retained. If both are shades of grey, then the pages can look _dirty_. I believe that this is true in general. 
- **use more yellow**. ansys.com uses black-and-white predominately but also uses more yellow than PyAnsys, and many ansys.com pages are very colourful within that conservative colour scheme. Our docs (speaking at least for PyFluent) contain little additional colour. This could be improved by using more yellow, and I think we should avoid mixing in any new colours. An extra band of yellow could liven up the appearance (similar to ansys.com). I believe that this could look good in light mode, especially if light mode were implemented as light mode, as mentioned above.

**Comment by RobPasMue** [comment]
> * **make light mode a true light mode**, which means that the navigation bar is white(ish), not black. Many people detest dark modes in general, so if people are choosing light mode, we should honour that.

I completely agree on this - we should try to search for a true light mode. Having that dark navigation bar on "light" mode is not what a user would expect. Going with a lighter shade of black like PyMAPDL's could be a good option.

> * **use shades of grey** instead of pure black-and-white, ... If both are shades of grey, then the pages can look _dirty_. I believe that this is true in general.

I agree as well! Only one of them should be toned down. We can see this in the new PyMAPDL docs. While I do like the lighter dark on the navigation bar, the "dirty" white is not that nice... I would have plain white there.

> * **use more yellow**. ansys.com uses black-and-white predominately but also uses more yellow than PyAnsys, and many ansys.com pages are very colourful within that conservative colour scheme.

Also, ansys documentation uses many different tones of yellow as far as I can tell... That would give us some room for manouvering

**Comment by jgd10** [comment]
Are there any UX experts we could bring in to this discussion? I think there are existing conventions we can, and probably should, follow regarding the color schemes.

**Comment by RobPasMue** [comment]
We've worked in the past with @timdansys - he might be able to chime in

**Comment by ClionaJC** [comment]
Hello everyone! 

Jérôme Blanche has kindly invited me to this conversation. 

I have no opinion on the first point, as I think there is a history behind it that I may not be aware of. 

If you are talking about using shades of grey, then you may be losing some colour contrast (and therefore potentially some users). 

In relation to the yellow it is a very inaccessible colour. I know that it is part of the branding, but failing needing to adhere to a template it is a bad idea to use yellow for linking, etc. 

If anyone wants me to explain either of the above points, please let me know.

**Comment by seanpearsonuk** [comment]
@ClionaJC Thanks!
At least some of have agreed that trying to contrast light grey with dark grey is not good, and I had proposed white with dark grey. Pure black and white is just not good.  
I don't mind between yellow and any other colour as long as we lift the appearance above the current drabness.

**Comment by Andy-Grigg** [comment]
Could we take inspiration from the ADL here? I realize fully overhauling the layout would be a lot of work, to the point at which we'd probably be writing a sphinx theme from scratch. But maybe the color palettes might be useful?

**Comment by ClionaJC** [comment]
@seanpearsonuk No problem. As in general rule, in what I was taught in my MA, the stronger you can make the colour contrast the better. However, I realise that there are also other affordances involved and that I am only joining this conversation now. 

I am still going to strongly object to the yellow though (you can, of course, take or leave this advice). It's one of the top inaccessible colours and, in my opinion, should not be used for sectioning text, or anything functional like linking.

**Comment by mia-guo-ux** [comment]
I agree with the idea that we could make light mode a true light mode. Designs have been updated. Please let me know what you think.
![PyMAPDL Home](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/280f2e72-dc06-4832-a049-2f93e1d00578)

**Comment by jorgepiloto** [comment]
Oh wow! That style looks gorgeous, @mia-guo-ux. I like it a lot. It even makes me think if we should only support light theme docs.

How do you devise the style for the rest of the pages? I would like to see how this lightgray background fits with the left and right sidebars we use for listing pages and sections.

**Comment by greschd** [comment]
Agreed, it looks very nice! A tiny nitpick: I think there should be _some_ visual distinction of the header bar. Maybe a thin line, or slightly different shade of grey?

**Comment by ClionaJC** [comment]
@greschd That makes sense to me. Both, if possible...

**Comment by ClionaJC** [comment]
@mia-guo-ux Great work, as usual... ;)

**Comment by Revathyvenugopal162** [comment]
> Agreed, it looks very nice! A tiny nitpick: I think there should be _some_ visual distinction of the header bar. Maybe a thin line, or slightly different shade of grey?
> 
> Or maybe not, I'm not an expert on these things 🙂

We can make use of the inherent header from pydata theme , a slight shadow box 
![image](https://github.com/ansys/ansys-sphinx-theme/assets/104772255/9c0dcbce-ad68-42e6-8c8e-a5d27197b688)
or our own box

**Comment by RobPasMue** [comment]
> We can make use of the inherent header from pydata theme , a slight shadow box ![image](https://private-user-images.githubusercontent.com/104772255/340233590-9c0dcbce-ad68-42e6-8c8e-a5d27197b688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTMyMzgsIm5iZiI6MTcxODYxMjkzOCwicGF0aCI6Ii8xMDQ3NzIyNTUvMzQwMjMzNTkwLTljMGRjYmNlLWFkNjgtNDJlNi04YzhlLWE1ZDI3MTk3YjY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwODI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGVmNDEwN2JjNmYwY2FmZWFhZWQxY2ZmNmM5ZmZiZTY4ZmM2MjlmYWM0Y2Y3NGY1ZmU3NDQyNDNmMGMwYTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qK6OjxSzqwungniLCRYQfizlRiom9c_B6O1tjYOT_ws)

I like the slight shadow approach honestly =)

**Comment by ClionaJC** [comment]
In case anyone has time/is interested this article in relation to cognitive load on a PC versus a mobile phone is quite relevant. If you only read the abstract and the conclusion it will give you some idea of what the study covered: https://link.springer.com/article/10.1007/s00779-022-01707-8

**Comment by germa89** [comment]
> I agree with the idea that we could make light mode a true light mode. Designs have been updated. Please let me know what you think. ![PyMAPDL Home](https://private-user-images.githubusercontent.com/123198029/339912559-280f2e72-dc06-4832-a049-2f93e1d00578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTY5OTUsIm5iZiI6MTcxODYxNjY5NSwicGF0aCI6Ii8xMjMxOTgwMjkvMzM5OTEyNTU5LTI4MGYyZTcyLWRjMDYtNDgzMi1hMDQ5LTJmOTNlMWQwMDU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwOTMxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWYwMjRjMzNlZDJmM2I5MDVhYTRiYjI1OGY3MDFmZDBhOTZiMmJlMjUzN2YyYzUyMDU3NTgwYjEwMTA3NWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ldTxIplAXAnYorml_iy3mF2SiRL6YPg1qiu4IqeH6w0)

![Omg](https://tenor.com/bhJqT.gif)

**Comment by seanpearsonuk** [comment]
For comparison, please also see [Vega-Altair light theme](https://altair-viz.github.io/index.html), which caught my eye in the presentation by @clatapie - I think it looks very smart, and motivated me to mekt the comments about light theme. All the separations are handled very nicely in this page.

**Comment by clatapie** [comment]
The following approach, displayed by [Vega](https://vega.github.io/vega/) is also interesting:
![image](https://github.com/ansys/ansys-sphinx-theme/assets/78221213/096845ab-9d4a-4656-aaa8-0881dacfd6ac)

We could imagine a drop-down button:
- with all the PyAnsys libraries - which might be too heavy 
- with the [PyAnsys website](https://docs.pyansys.com/) and the [PyAnsys dev guide](https://dev.docs.pyansys.com/).

**Comment by greschd** [comment]
> We could imagine a drop-down button: [...] with the PyAnsys website and the PyAnsys dev guide

What if every PyAnsys library (optionally) gets to add 2-3 closely related projects to this drop-down? For example, PyDPF Composites would probably add:
- PyACP (pre-processor)
- DPF Core

So the full list would be 
- PyACP
- DPF Core
- All PyAnsys projects (link to PyAnsys website)
- PyAnsys dev guide

**Comment by MaxJPRey** [comment]
@greschd I agree with this idea.
It might help promote other tools that are usually related in workflows and help users to navigate to what they are interested in.

I would just suggest to put at first

- All PyAnsys projects (link to PyAnsys website)
- PyAnsys dev guide

So it stays consistent across libraries.

**Comment by MaxJPRey** [comment]
> > We can make use of the inherent header from pydata theme , a slight shadow box ![image](https://private-user-images.githubusercontent.com/104772255/340233590-9c0dcbce-ad68-42e6-8c8e-a5d27197b688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTMyMzgsIm5iZiI6MTcxODYxMjkzOCwicGF0aCI6Ii8xMDQ3NzIyNTUvMzQwMjMzNTkwLTljMGRjYmNlLWFkNjgtNDJlNi04YzhlLWE1ZDI3MTk3YjY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwODI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGVmNDEwN2JjNmYwY2FmZWFhZWQxY2ZmNmM5ZmZiZTY4ZmM2MjlmYWM0Y2Y3NGY1ZmU3NDQyNDNmMGMwYTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qK6OjxSzqwungniLCRYQfizlRiom9c_B6O1tjYOT_ws)
> 
> I like the slight shadow approach honestly =)

I agree. The shadow do a good things when used as a separator between elements.

**Comment by mia-guo-ux** [comment]
Here are some additional screens, with updates to side nav, card style and page header. In addition, there are some design suggestion added to this [issue ](https://github.com/ansys/ansys-sphinx-theme/issues/403)
![PyAnsys](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/208372fb-73d2-4e80-9874-1a9eeec84806)
![Home](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/f8cc3a75-e616-4959-a98d-db53c1b8beb1)
![Page](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/0ba14edd-08fb-4ba6-8e2f-7a1ad8713ff1)

**Comment by ClionaJC** [comment]
@mia-guo-ux The graphics on the first page are beautiful!

It's also very helpful for me to see how other people are writing instructions.

**Comment by jorgepiloto** [comment]
Closing this in favor of 403.
