### ISSUE TITLE
Ansys Sphinx Theme - Design updates

### ISSUE THREAD

**Issue by mia-guo-ux** [ansys/ansys-sphinx-theme#403]
**Sphinx design** : https://sphinxdocs.ansys.com/version/dev/examples/sphinx-design.html#

The following components could be enhanced to create a more streamlined user experience. 
- Cards (including card carousel)
- Buttons 
- Links
- Side navigation
- Selector 
- Dropdown 
- Table
- etc.

Please feel free to let me know if you have any concerns or if anything needs to be specified. Cheers!
FYI @Revathyvenugopal162 @jorgepiloto @RobPasMue

**Comment by mia-guo-ux** [comment]
**Card**
![Home](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/20ceb8fd-0542-4b2f-a555-e6b0bd931e2c)

**Comment by mia-guo-ux** [comment]
**Buttons**
![Buttons](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/6e76a1a0-5ff4-4c0a-8486-2646864015fe)

**Comment by mia-guo-ux** [comment]
**Links**
![Links](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/7a750571-5980-43fa-81ac-e722e6d19a9e)

**Comment by mia-guo-ux** [comment]
**Side nav**
![Side nav](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/de6f591a-2c80-4699-8a8e-288e0d5f68a0)

**Comment by mia-guo-ux** [comment]
**Select**
![Selector](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/a43a1a53-8070-4406-b668-1775b556ec75)

**Comment by mia-guo-ux** [comment]
**Dropdown**
![Dropdown](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/ce7fd89f-096c-47fb-84d7-84a8f1b52d2d)

**Comment by mia-guo-ux** [comment]
**Table**
![Table](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/14085dfe-cce8-45fc-aad5-805fc090378d)

**Comment by mia-guo-ux** [comment]
**Scrollbar**
![Scrollbar](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/2fc33f7d-524f-4c08-969d-bc6183144c99)

**Comment by mia-guo-ux** [comment]
**Breadcrumb**
![Breadcrumb](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/06177238-f819-4c79-8f4e-0c887d25ea69)

**Comment by mia-guo-ux** [comment]
**Tabs**
![Tabs](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/ae7f81df-e05b-401a-9562-997ac9bd0e7f)

**Comment by mia-guo-ux** [comment]
**Generic guidelines**
![Generic](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/4849c29e-51bd-4675-954f-31abacb3bdb2)

**Comment by mia-guo-ux** [comment]
Example pages
![Page](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/165beef5-028c-427b-accb-39edea874cf7)
![PyAnsys](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/d3d53422-b5bf-42c3-8171-4dd674563027)
![Home](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/011646ce-e014-40b5-a71d-a7132e982f02)

**Comment by jorgepiloto** [comment]
Thanks for this great review, @mia-guo-ux. 

The only thing I do not agree is the `text-align` of the code blocks content. In my opinion, this should be left-aligned. Otherwise, we are loosing a precious space. Some statements can be quite long, so it is better to use all the available space. I am fine though adding some padding. What do you think?

**Comment by RobPasMue** [comment]
> Thanks for this great review, @mia-guo-ux.
> 
> The only thing I do not agree is the text-align of the code blocks content. In my opinion, this should be left-aligned. Otherwise, we are loosing a precious space. Some statements can be quite long, so it is better to use all the available space. I am fine though adding some padding. What do you think?

I agree with Jorge - code-snippets should be left aligned IMO

**Comment by mia-guo-ux** [comment]
Great catch! Here's an updated screen. Besides this, please feel free to let me know if any of the updates is technically feasible and if any adjustment is needed :)
![Page](https://github.com/ansys/ansys-sphinx-theme/assets/123198029/c8ddd115-6e96-4fc2-96cf-3a35603dcf78)

**Comment by RobPasMue** [comment]
Have we addressed all the changes @Revathyvenugopal162 @jorgepiloto ?

**Comment by PipKat** [comment]
> > Thanks for this great review, @mia-guo-ux.
> > The only thing I do not agree is the text-align of the code blocks content. In my opinion, this should be left-aligned. Otherwise, we are loosing a precious space. Some statements can be quite long, so it is better to use all the available space. I am fine though adding some padding. What do you think?
> 
> I agree with Jorge - code-snippets should be left aligned IMO

Code blocks, captions, tables -- all should be left-aligned!

**Comment by mia-guo-ux** [comment]
The code snippet has been fixed. Please let me know if anything needs to be updated. :)

**Comment by Revathyvenugopal162** [comment]
> **Table** ![Table](https://private-user-images.githubusercontent.com/123198029/341215944-14085dfe-cce8-45fc-aad5-805fc090378d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1OTQ0LTE0MDg1ZGZlLWNjZTgtNDVmYy1hYWQ1LTgwNWZjMDkwMzc4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTM1ZDAzYjhiMDJkODE1MzA1ODliNjNmMTdiMjgwY2U3N2NjYzZkMTNhOWYxMmFmMWQ5YjBiODhhZTkwMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tOA7NtQuIbb3UgbUaROVJgxtMrYBeuAcN6z-7KCEOfA)

PR #408

**Comment by Revathyvenugopal162** [comment]
> **Generic guidelines** ![Generic](https://private-user-images.githubusercontent.com/123198029/341216285-4849c29e-51bd-4675-954f-31abacb3bdb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE2Mjg1LTQ4NDljMjllLTUxYmQtNDY3NS05NTRmLTMxYWJhY2IzYmRiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2M1MTI4NDliZTI1NTNmMzlmZDc2MmExNDUxNTViN2E0NTkxMjE0OGZhYjVmNzYwOGI4YTI4NTA3MTU0Zjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H5ElFFSvCyK_29wRuCFuoYODUvFLDJfvPmR3HR-cErM)

PR #409

**Comment by Revathyvenugopal162** [comment]
> **Side nav** ![Side nav](https://private-user-images.githubusercontent.com/123198029/341215602-de6f591a-2c80-4699-8a8e-288e0d5f68a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NjAyLWRlNmY1OTFhLTJjODAtNDY5OS04YThlLTI4OGUwZDVmNjhhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGRhYWY5YjRjY2E4MjBmODM5YWU2Y2MzNDhkZjQ4ZjI1NDk0ZmI5NTRmMmQ1OGY1ZTk0MWIxNTU1MmYzZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNM_xezORbVvwAhGqmjZY8ihrKmNExuOT1BvJk8r2RM)

PR https://github.com/ansys/ansys-sphinx-theme/pull/411

**Comment by Revathyvenugopal162** [comment]
> > **Side nav** ![Side nav](https://private-user-images.githubusercontent.com/123198029/341215602-de6f591a-2c80-4699-8a8e-288e0d5f68a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NjAyLWRlNmY1OTFhLTJjODAtNDY5OS04YThlLTI4OGUwZDVmNjhhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGRhYWY5YjRjY2E4MjBmODM5YWU2Y2MzNDhkZjQ4ZjI1NDk0ZmI5NTRmMmQ1OGY1ZTk0MWIxNTU1MmYzZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNM_xezORbVvwAhGqmjZY8ihrKmNExuOT1BvJk8r2RM)
> 
> PR #411

@mia-guo-ux , the color you mentioned for the active and hover states in the sidebar is the same, but it appears different in the image. Could you please clarify?

**Comment by Revathyvenugopal162** [comment]
> **Side nav** ![Side nav](https://private-user-images.githubusercontent.com/123198029/341215602-de6f591a-2c80-4699-8a8e-288e0d5f68a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NjAyLWRlNmY1OTFhLTJjODAtNDY5OS04YThlLTI4OGUwZDVmNjhhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGRhYWY5YjRjY2E4MjBmODM5YWU2Y2MzNDhkZjQ4ZjI1NDk0ZmI5NTRmMmQ1OGY1ZTk0MWIxNTU1MmYzZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNM_xezORbVvwAhGqmjZY8ihrKmNExuOT1BvJk8r2RM)

@mia-guo-ux , the color you mentioned for the active and hover states in the sidebar is the same, but it appears different in the image. Could you please clarify?

**Comment by Revathyvenugopal162** [comment]
> **Links** ![Links](https://private-user-images.githubusercontent.com/123198029/341215561-7a750571-5980-43fa-81ac-e722e6d19a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NTYxLTdhNzUwNTcxLTU5ODAtNDNmYS04MWFjLWU3MjJlNmQxOWE5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmQwOWZiNDlkMmRmNjEzNTIyYjYwNzZhMzE5YmQxYmRlYTEwZDBmZjc5MWJiYzI0ZmIxMWU0ZWE5MzMxOTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6fNS1CCG7Rpm4pseOdj_ztyXqBhWVjS22H6MFrrH8c8)

@mia-guo-ux , For links, we have two additional states: visited links and visited hover links. Could you please check these and provide design suggestions for them as well?

**Comment by mia-guo-ux** [comment]
> > **Side nav** ![Side nav](https://private-user-images.githubusercontent.com/123198029/341215602-de6f591a-2c80-4699-8a8e-288e0d5f68a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NjAyLWRlNmY1OTFhLTJjODAtNDY5OS04YThlLTI4OGUwZDVmNjhhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGRhYWY5YjRjY2E4MjBmODM5YWU2Y2MzNDhkZjQ4ZjI1NDk0ZmI5NTRmMmQ1OGY1ZTk0MWIxNTU1MmYzZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNM_xezORbVvwAhGqmjZY8ihrKmNExuOT1BvJk8r2RM)
> 
> @mia-guo-ux , the color you mentioned for the active and hover states in the sidebar is the same, but it appears different in the image. Could you please clarify?

Sorry for the confusion. The image has been updated. In Hover states, the bg fill is #ECECEC, but in Active states, it should be #D9D9D9

**Comment by mia-guo-ux** [comment]
> > **Links** ![Links](https://private-user-images.githubusercontent.com/123198029/341215561-7a750571-5980-43fa-81ac-e722e6d19a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg0NjcsIm5iZiI6MTcxOTgxODE2NywicGF0aCI6Ii8xMjMxOTgwMjkvMzQxMjE1NTYxLTdhNzUwNTcxLTU5ODAtNDNmYS04MWFjLWU3MjJlNmQxOWE5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmQwOWZiNDlkMmRmNjEzNTIyYjYwNzZhMzE5YmQxYmRlYTEwZDBmZjc5MWJiYzI0ZmIxMWU0ZWE5MzMxOTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6fNS1CCG7Rpm4pseOdj_ztyXqBhWVjS22H6MFrrH8c8)
> 
> @mia-guo-ux , For links, we have two additional states: visited links and visited hover links. Could you please check these and provide design suggestions for them as well?

The design has been updated. 
- Visited state: Open sans regular, 14px, #9A33CB
- Visited hover state: Open sans regular, 14px, #7B29A2

**Comment by mia-guo-ux** [comment]
Hi @Revathyvenugopal162 
I made a few updates to Tabs, Side nav, Links, and Global Nav. Please refer to the original post (the images have been re-uploaded). Thank you :)

**Comment by Revathyvenugopal162** [comment]
> **Links** ![Links](https://private-user-images.githubusercontent.com/123198029/344756320-e3f62ce4-385d-48d5-b82e-61c1ea3d4390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTExNjksIm5iZiI6MTcxOTkxMDg2OSwicGF0aCI6Ii8xMjMxOTgwMjkvMzQ0NzU2MzIwLWUzZjYyY2U0LTM4NWQtNDhkNS1iODJlLTYxYzFlYTNkNDM5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTAxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDY4ODM3ZjM0MDQ5MDUyZjUyMWEzYWRmZDNhMDhhMWM2YTg1NDM3ZWU1ODdhOTM1NjViYWJlMTJhMTQ0YzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.duo2kh6GOkVO7ztcjSy39YwzTxHeCpt7gThB8CBfYpM)

PR 411

**Comment by Revathyvenugopal162** [comment]
Task list
- [ ] [Cards](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179521916)
- [ ] [Buttons](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179522340)
- [ ] [Links](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179522562) - #411
- [ ] [Sidebar](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179522785) - #411
- [ ] [Dropdown](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179523065)
- [ ] [Table](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179524578) - #408 
- [ ] [Scrollbar](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179525335)
- [ ] [Breadcrumbs](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179525496)
- [ ] [Tabs](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179525609)
- [ ] [General layout](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179526072) - #409, #411

**Comment by jorgepiloto** [comment]
Hi @mia-guo-ux, could you also propose some style for our search bar? When pressing "Ctrl + k", an interactive search opens up. As soon as users type anything, it suggests different results. Right now, its style is out of sync with the rest of the theme.

**Comment by mia-guo-ux** [comment]
@jorgepiloto Sure. Please see below. I was also wondering can we remove the popup 
![image](https://github.com/user-attachments/assets/9309fae0-16cf-4d23-a10e-7dd265b9aff2)
and allow search behaviors in the input box only?
![Search](https://github.com/user-attachments/assets/e0a93ef9-9ad4-4333-8986-300bc8064a55)

**Comment by jorgepiloto** [comment]
The pop-up is a desired feature requested by many customers and developers. We are using MeiliSearch to provide fast and solid search results. Thus, the need for styling it too.

**Comment by Revathyvenugopal162** [comment]
> Hi @Revathyvenugopal162 I made a few updates to Tabs, Side nav, Links, and Global Nav. Please refer to the original post (the images have been re-uploaded). Thank you :)
> 
> In addition, here's the admonition component ![Admonitions](https://private-user-images.githubusercontent.com/123198029/344826472-6b438b84-704f-423d-9cd1-ef6b3db8ad7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjI2OTYsIm5iZiI6MTcyMjg2MjM5NiwicGF0aCI6Ii8xMjMxOTgwMjkvMzQ0ODI2NDcyLTZiNDM4Yjg0LTcwNGYtNDIzZC05Y2QxLWVmNmIzZGI4YWQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMjUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzE3ZDcwMzU4YjIxMzA0MzRjMDMwNmFmMWM5ZjhjNmY0YWE0YzczYTNmNjg2ZWM1YjBmNzg0NmIxOGQ5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q7vxq2F51fk85M_rVqO8TlksJysDGlT-OfHlIRNzAbY)

@mia-guo-ux , there was a question regarding the yellow color and why we are not using the Ansys Gold. Do you have any particular reason for not selecting that border? If so, could you please share it here or revert the color to Ansys Gold? I'm also looping in the docs team since this question arose from the docs team meeting. Pinging @ansys/pyansys-core @ansys/documentation

**Comment by mia-guo-ux** [comment]
> > Hi @Revathyvenugopal162 I made a few updates to Tabs, Side nav, Links, and Global Nav. Please refer to the original post (the images have been re-uploaded). Thank you :)
> > In addition, here's the admonition component ![Admonitions](https://private-user-images.githubusercontent.com/123198029/344826472-6b438b84-704f-423d-9cd1-ef6b3db8ad7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjI2OTYsIm5iZiI6MTcyMjg2MjM5NiwicGF0aCI6Ii8xMjMxOTgwMjkvMzQ0ODI2NDcyLTZiNDM4Yjg0LTcwNGYtNDIzZC05Y2QxLWVmNmIzZGI4YWQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMjUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzE3ZDcwMzU4YjIxMzA0MzRjMDMwNmFmMWM5ZjhjNmY0YWE0YzczYTNmNjg2ZWM1YjBmNzg0NmIxOGQ5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q7vxq2F51fk85M_rVqO8TlksJysDGlT-OfHlIRNzAbY)
> 
> @mia-guo-ux , there was a question regarding the yellow color and why we are not using the Ansys Gold. Do you have any particular reason for not selecting that border? If so, could you please share it here or revert the color to Ansys Gold? I'm also looping in the docs team since this question arose from the docs team meeting. Pinging @ansys/pyansys-core @ansys/documentation

Were you referring to the border color of the warning alert? Typically, we apply Ansys Gold exclusively to brand-relevant elements such as logos. In the design language, we have yellow as the dedicated color for warning states.

**Comment by Revathyvenugopal162** [comment]
> > > Hi @Revathyvenugopal162 I made a few updates to Tabs, Side nav, Links, and Global Nav. Please refer to the original post (the images have been re-uploaded). Thank you :)
> > > In addition, here's the admonition component ![Admonitions](https://private-user-images.githubusercontent.com/123198029/344826472-6b438b84-704f-423d-9cd1-ef6b3db8ad7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjI2OTYsIm5iZiI6MTcyMjg2MjM5NiwicGF0aCI6Ii8xMjMxOTgwMjkvMzQ0ODI2NDcyLTZiNDM4Yjg0LTcwNGYtNDIzZC05Y2QxLWVmNmIzZGI4YWQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMjUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzE3ZDcwMzU4YjIxMzA0MzRjMDMwNmFmMWM5ZjhjNmY0YWE0YzczYTNmNjg2ZWM1YjBmNzg0NmIxOGQ5MzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q7vxq2F51fk85M_rVqO8TlksJysDGlT-OfHlIRNzAbY)
> > 
> > 
> > @mia-guo-ux , there was a question regarding the yellow color and why we are not using the Ansys Gold. Do you have any particular reason for not selecting that border? If so, could you please share it here or revert the color to Ansys Gold? I'm also looping in the docs team since this question arose from the docs team meeting. Pinging @ansys/pyansys-core @ansys/documentation
> 
> @Revathyvenugopal162 Were you referring to the border color of the warning alert? Typically, we apply Ansys Gold exclusively to brand-relevant elements such as logos. In the design language, we have yellow as the dedicated color for warning states.

Thank you for explanation. It was to check why we using a dedicated yellow.

**Comment by jorgepiloto** [comment]
We finally released version v1.0. Mind you performing one last review, @mia-guo-ux so we can close this?

**Comment by mia-guo-ux** [comment]
> We finally released version v1.0. Mind you performing one last review, @mia-guo-ux so we can close this?
