### ISSUE TITLE
 Add examples for all reformatted extensions in theme

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#404]
To enhance the documentation and usability of the Ansys Sphinx theme,  provide comprehensive examples for all extensions whose styles have been reformatted in this theme.

**Comment by jorgepiloto** [comment]
Can we close this issue, @Revathyvenugopal162?

**Comment by Revathyvenugopal162** [comment]
yes, i linked the PRs
