### ISSUE TITLE
``[autoapi]`` target and extension does not add the needed extensions by default

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#464]
See https://github.com/ansys/pyansys-tools-versioning/pull/280

It looks like the extension developed does not include properly the other required extensions ``sphinx-design`` in this specific case. Until I added it manually, the build process kept complaining of not knowing what tab-set is...

It seems that we are not extending the used extensions properly. @Revathyvenugopal162 could you investigate this?

**Comment by RobPasMue** [comment]
Before adding the extension: https://github.com/ansys/pyansys-tools-versioning/actions/runs/10367469186/job/28698973488
After adding the extension: https://github.com/ansys/pyansys-tools-versioning/actions/runs/10367511971/job/28699114271

**Comment by Revathyvenugopal162** [comment]
> See [ansys/pyansys-tools-versioning#280](https://github.com/ansys/pyansys-tools-versioning/pull/280)
> 
> It looks like the extension developed does not include properly the other required extensions `sphinx-design` in this specific case. Until I added it manually, the build process kept complaining of not knowing what tab-set is...
> 
> It seems that we are not extending the used extensions properly. @Revathyvenugopal162 could you investigate this?

sure, i will look in to it
