### ISSUE TITLE
revisit the header sizes

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#483]
Header H2 and H3 have the almost same sizes which makes the content structure difficult to differentiate
example page https://sphinxdocs.ansys.com/version/stable/user-guide/configuration.html
_(originally discussed in docs team meeting)_

**Comment by mia-guo-ux** [comment]
@Revathyvenugopal162 

Please refer to the typography sheets below. **Typography-PyAnsys** is based on the current typefaces we have on PyAnsys webpages, and **Typography-AWC** is what we have in Ansys Web Components design library. Please feel free to pin me if you have any questions.
![Typography - PyAnsys](https://github.com/user-attachments/assets/15b54500-1d65-4e87-8ef6-fb3dff752b30)
![Typography - AWC](https://github.com/user-attachments/assets/bc8f3b3b-2aef-4a2c-b843-f3b38a8d1194)

**Comment by Revathyvenugopal162** [comment]
thank you for the topography @mia-guo-ux
