### ISSUE TITLE
Phone view crops sidebar menu

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#492]
See screenshot

![image](https://github.com/user-attachments/assets/8dcf57cc-f2f0-4ffa-8842-c1cf6e281471)

The leftbar menu now has an impossible to use scrollbar on phone view. Let's adapt it to look like the rightbar menu. See:

![image](https://github.com/user-attachments/assets/fb98421f-ce32-4caf-bbb2-75bf3b24d3eb)

**Comment by Revathyvenugopal162** [comment]
@mia-guo-ux could you please look at this issue and give us the layout on standards?

**Comment by mia-guo-ux** [comment]
@Revathyvenugopal162 @RobPasMue 

We could use a hamburger menu for page side nav. This is also seen on [Mozilla](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps#assessments), [Microsoft](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), and [Apple](https://developer.apple.com/documentation/AppIntents/Integrating-your-app-with-siri-and-apple-intelligence).

### **Mobile view**
![Mobile](https://github.com/user-attachments/assets/8043bff1-8d09-46c5-8b15-c15d18cba2ef)

### **Mobile top nav**
![Mobile - Main menu](https://github.com/user-attachments/assets/26bbcd31-d58c-4b4b-888a-ee246d65e785)

### **Mobile side nav**
![Mobile - Page side nav](https://github.com/user-attachments/assets/28352daa-5546-4126-bed8-24c9b021564a)

**Comment by RobPasMue** [comment]
Awesome, thanks!
