### ISSUE TITLE
Allow developers to skip the build of the examples

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#526]
Every time the documentation of this project is built, various requests get performed to fetch third party examples.

Multiple runs lead to these third parties blocking for 5 min any additional requests.

We should allow to skip the build of the examples via the Jinja approach we have in other projects.

### Note

Before contributing and starting any work, please make sure you agree with the [CLA](https://developer.ansys.com/form/cla-acceptance) and sign it in your PR.

**Comment by Revathyvenugopal162** [comment]
**Steps to Implement:**

- [ ]  Ensure that `sphinx_jinja` is included as a dependency in pyproject.toml (it is already present).
- [ ] Implement Build Example Environment Variable: https://github.com/ansys/pyansys-geometry/blob/main/doc/source/conf.py#L353
- [ ] Update `examples.rst`: https://github.com/ansys/pyansys-geometry/blob/main/doc/source/index.rst?plain=1#L41
**Acceptance Criteria:**

- [ ] - The build process can successfully skip examples based on the environment variable.
- [ ] - The Jinja template is properly integrated and functioning in `index.rst`.
- [ ] - All changes are tested, and documentation is updated accordingly.
