### ISSUE TITLE
Refactor CSS to use ansys-sphinx-theme variables

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#531]
Description:
Clean up the existing CSS files by removing all hardcoded values (e.g., colors, fonts, spacings) and migrate them to use variables defined in the [ansys-sphinx-theme variables.css file](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css). This will ensure consistency across the theme and make future maintenance easier.

Acceptance Criteria:

- [ ] Identify and replace hardcoded values in the CSS files with variables from variables.css.
- [ ] Test the visual appearance to ensure no discrepancies are introduced.

### Note

Before contributing and starting any work, please make sure you agree with the [CLA](https://developer.ansys.com/form/cla-acceptance) and sign it in your PR.

**Comment by Abhinav-gh** [comment]
Hello! I am actively participating in HacktoberFest2024. I would like to work on this. Could you please assign this issue to me? Thanks!

**Comment by SMoraisAnsys** [comment]
> Hello! I am actively participating in HacktoberFest2024. I would like to work on this. Could you please assign this issue to me? Thanks!

Hi @Abhinav-gh, thanks for contributing to this repo. I'm assigning you to this issue.
Please, ensure to look at the note of this issue and agreeing with the [CLA](https://developer.ansys.com/form/cla-acceptance) before contributing.
