### ISSUE TITLE
Use Jinja macros in `autoapi.rst` file for customization

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#533]
**Description:**  
Implement Jinja macros in the `autoapi.rst` file: https://github.com/ansys/ansys-sphinx-theme/tree/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi to streamline and customize the content generation for API documentation. Using Jinja macros will help create reusable templates, reduce code duplication, and enhance maintainability of the `.rst` files.

**Acceptance Criteria:**

- [ ] Create Jinja macros for repetitive content blocks in the `autoapi.rst` file.
- [ ] Replace existing content with appropriate macros.
- [ ] Verify that the `autoapi.rst` renders correctly using the new macros.
- [ ] Ensure the documentation structure and formatting remain consistent.

### Note

Before contributing and starting any work, please make sure you agree with the [CLA](https://developer.ansys.com/form/cla-acceptance) and sign it in your PR.

**Comment by jorgepiloto** [comment]
We already have macros in those files. Are we missing any additional macros, @Revathyvenugopal162?
