### ISSUE TITLE
Remove unused example files from `ansys-sphinx-theme/src/ansys_sphinx_theme/examples`

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#536]
**Description:**  
Delete the example files located in [`ansys-sphinx-theme/src/ansys_sphinx_theme/examples`](https://github.com/ansys/ansys-sphinx-theme/tree/main/src/ansys_sphinx_theme/examples) as they are not utilized in the library. These files are only referenced in the development guide, which is not required for the main functionality of the theme.

**Acceptance Criteria:**

- [ ] Locate and remove all files in the `ansys-sphinx-theme/src/ansys_sphinx_theme/examples` directory.
- [ ] Ensure that the removal does not affect any existing documentation or functionality.
- [ ] Confirm that the repository structure is clean and only includes necessary files.

### Note

Before contributing and starting any work, please make sure you agree with the [CLA](https://developer.ansys.com/form/cla-acceptance) and sign it in your PR.

**Comment by Abhinav-gh** [comment]
Hey! I have already set up the project. Could this be assigned to me?

**Comment by RobPasMue** [comment]
Hi @Abhinav-gh - thanks for volunteering! Please remember to check the [CLA](https://developer.ansys.com/form/cla-acceptance) and sign it. Apart from that, all good! You've been assigned this task.

**Comment by jorgepiloto** [comment]
@Revathyvenugopal162, I just realized that we are using those for rendering the API reference.
