### ISSUE TITLE
TOC tree of API moves a bit to the right when clicked

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [ansys/ansys-sphinx-theme#543]
When you click on an element of the ToC tree of the API reference, it moves a bit to the left, making it look like it's the children of the element on top.

[Screen Recording - Made with FlexClip.webm](https://github.com/user-attachments/assets/373c456a-ae40-4bc5-90a3-c4165dd6ea70)

**Comment by jorgepiloto** [comment]
@AlejandroFernandezLuces, could you confirm against current `v1.2.dev0` that this is working for you?

**Comment by AlejandroFernandezLuces** [comment]
Working nicely for me: 
![image](https://github.com/user-attachments/assets/fd2d2b7f-79c5-4052-8c42-276c618c2605)

Thanks for the hard work @Revathyvenugopal162 🚀
