### ISSUE TITLE
Rendering issue with `\mathit` in `math` role

### ISSUE THREAD

**Issue by ansbmartin** [ansys/ansys-sphinx-theme#544]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When using `\mathit{}` in a `:math:` role, the content of `mathit` is truncated on the right.

Example:
```rst
- Example 1: :math:`\mathit{f}`.
- Example 2: :math:`\mathit{H}` test.
```

![image](https://github.com/user-attachments/assets/12c25ded-c85c-4499-a552-dca81baa4e26)

The same file is rendered correctly with the `alabaster` theme:
![image](https://github.com/user-attachments/assets/a8cb6b14-16c7-419e-8c0e-096b3d83882b)

### 📝 Steps to reproduce

1. unzip [ansys-theme-math.zip](https://github.com/user-attachments/files/17340075/ansys-theme-math.zip)
2. run `sphinx-build -M html . _build`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Ansys Sphinx theme 1.1.2

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
accessible-pygments==0.0.5
alabaster==1.0.0
ansys-sphinx-theme==1.1.2
babel==2.16.0
beautifulsoup4==4.12.3
certifi==2024.8.30
charset-normalizer==3.4.0
colorama==0.4.6
docutils==0.21.2
idna==3.10
imagesize==1.4.1
importlib_metadata==8.5.0
Jinja2==3.1.4
MarkupSafe==3.0.1
packaging==24.1
pdf2image==1.17.0
pillow==10.4.0
pydata-sphinx-theme==0.15.4
Pygments==2.18.0
requests==2.32.3
snowballstemmer==2.2.0
soupsieve==2.6
Sphinx==8.1.0
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
typing_extensions==4.12.2
urllib3==2.2.3
zipp==3.20.2
```

**Comment by jorgepiloto** [comment]
Thanks for reporting this @ansbmartin.Looks like this may be caused by the font we are using in our theme.
