### ISSUE TITLE
Monospaced font is not used for `code` and `literal` roles

### ISSUE THREAD

**Issue by ansbmartin** [ansys/ansys-sphinx-theme#548]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

With the following RST file:
```rst
- double backquotes: ``mmmm + iiii``
- code role: :code:`mmmm + iiii`
- literal role: :literal:`mmmm + iiii`
```

I would expect that a monospaced font is used, but this is not the case:
![image](https://github.com/user-attachments/assets/8023add9-c5a8-413d-83b2-b641056bf98e)

Note that the default `alabaster` theme uses a monospaced font:
![image](https://github.com/user-attachments/assets/bfcaf920-8d8b-4fa2-a414-977ea97f13f1)

### 📝 Steps to reproduce

- unzip [ansys-theme-monospaced.zip](https://github.com/user-attachments/files/17366027/ansys-theme-monospaced.zip)
- run `sphinx-build -M html . _build`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ansys-sphinx-theme==1.1.4

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
accessible-pygments==0.0.5
alabaster==1.0.0
ansys-sphinx-theme==1.1.4
babel==2.16.0
beautifulsoup4==4.12.3
certifi==2024.8.30
charset-normalizer==3.4.0
colorama==0.4.6
docutils==0.21.2
idna==3.10
imagesize==1.4.1
importlib_metadata==8.5.0
Jinja2==3.1.4
MarkupSafe==3.0.1
packaging==24.1
pdf2image==1.17.0
pillow==10.4.0
pydata-sphinx-theme==0.15.4
Pygments==2.18.0
requests==2.32.3
snowballstemmer==2.2.0
soupsieve==2.6
Sphinx==8.1.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
typing_extensions==4.12.2
urllib3==2.2.3
zipp==3.20.2
```

**Comment by jorgepiloto** [comment]
Thanks, @ansbmartin. This issue is solved in https://github.com/ansys/ansys-sphinx-theme/pull/537. It is not the original intend but using the variables fix this.

**Comment by Revathyvenugopal162** [comment]
> Pinging [@Revathyvenugopal162](https://github.com/Revathyvenugopal162) and [@jorgepiloto](https://github.com/jorgepiloto) -- [@ansbmartin](https://github.com/ansbmartin) reached out offline. This issue seems to have reappeared with the latest 1.5.2 release... Could we investigate?

Thank you for followup @RobPasMue  and @ansbmartin Sure i will investigate and adapt the solution. We changed the code blocks to monospace and for literal ones, we need to adapt that
