### ISSUE TITLE
Links inside grid cards do not work

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#552]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The links in the gridcards do not work... 

<img width="355" alt="image" src="https://github.com/user-attachments/assets/a6e11455-2047-40b0-a50e-d57c07cbae3e">

I thought they do .... or at least they did.

### 📝 Steps to reproduce

Go to: https://mapdl.docs.pyansys.com/version/dev/index.html

And try to use any of the links inside the cards 

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by RobPasMue** [comment]
I've seen this behavior before too... Don't know if we can control it though.

**Comment by MaxJPRey** [comment]
@Revathyvenugopal162 we most likely need your expertise on this 😄

**Comment by Revathyvenugopal162** [comment]
> It seems the links get "hidden" behind the gridcard clicking feature.

It should work, i can investigate on this

**Comment by jorgepiloto** [comment]
As discussed in a private meeting, we can play with JS to inspect any "sd-card" object and apply any required modifications. This is not ideal, but there is no other option with the current status of Sphinx Design.

**Comment by RobPasMue** [comment]
If it's not ideal I don't know if we should do it honestly. I'm fine with the current behavior, to be clear.

**Comment by jorgepiloto** [comment]
Maybe we could discourage having links inside of the cards, @RobPasMue.

**Comment by RobPasMue** [comment]
> Maybe we could discourage having links inside of the cards, [@RobPasMue](https://github.com/RobPasMue).

Agreed yeah - that might be the best =)

**Comment by germa89** [comment]
Can we subclass the directive?

I think we might... 

Anyway, it is not priority.

**Comment by greschd** [comment]
I would wonder what UX's perspective is on this. 

Having links inside an already-clickable element seems like an anti-pattern to me, but I might well be wrong on that.

**Comment by germa89** [comment]
Loool... we just need to remove the linking so it works as expected:

```rst
.. added link to the box
    .. grid-item-card:: :fa:`book` Learn how to use PyMAPDL
        :link: ref_learning
        :link-type: ref

        Check our :ref:`ref_learning` section.
        It is recommended you follow the
        :ref:`ref_pymapdl_course` course.

.. not linking the box
    .. grid-item-card:: :fa:`terminal` Learn how to get started

        Check our :ref:`ref_getting_started` section to learn to
        :ref:`ref_using_standard_install`, :ref:`ref_pymapdl_installation`,
        and :ref:`ref_launch_pymapdl`.
```

I'm closing this issue.
