### ISSUE TITLE
Consider moving the DNS domain from pyansys.com to ansys.com

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#62]
### Description of the feature

Once the repo is located inside the Ansys org, the CNAME used to host the documentation should be updated. We should be pointing towards https://sphinxdocs.ansys.com/ instead of https://sphinxdocs.pyansys.com/

In order to do this, we should perform a request to the department in charge of the domain ansys.com. Or whomever has access to it. In my case, I only have access to pyansys.com. Otherwise, I could do it myself. Who should we ping for this?

Pinging PyAnsys developers @akaszynski @MaxJPRey @jorgepiloto @Revathyvenugopal162 

### Steps for implementing the feature

First, this repository should be located in the Ansys org.
Then, request CNAME for DNS domain.
Finally, change the custom domain in GitHub Pages for this repository and adapt the links in the main page.

**Comment by RobPasMue** [comment]
I'll do this myself once I clarify with @chadqueen how to do it. Assigning the issue.

**Comment by RobPasMue** [comment]
ansys-sphinx-theme moved from PyAnsys to Ansys org.. I'll work on this next week.

**Comment by RobPasMue** [comment]
Assigning @Revathyvenugopal162 to create new domain. Link to docs: https://dev.docs.ansys.com/contents/ansys_best_practices/code_management/github/github_pages.html?highlight=dns#ansys-com-domain

**Comment by RobPasMue** [comment]
Any news on this @Revathyvenugopal162 ?

**Comment by Revathyvenugopal162** [comment]
@RobPasMue No updates from their side . I requested on last Friday.

**Comment by RobPasMue** [comment]
Closing since it has already been solved :)
