### ISSUE TITLE
Explore shipping a 404.rst

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#72]
🐞 **Problem**
When a page or link is broken, it would be interesting to show a custom 404 page. For this purpose, the [notfound.extension](https://pypi.org/project/sphinx-notfound-page/) is used.

However, previous extensions requires to pass the path to a 404.rst file:

```python
notfound_template = "404.rst"
```

This situation forces projects need to store a custom `404.rst` file, see [PyMAPDL custom 404.rst file](https://raw.githubusercontent.com/pyansys/pymapdl/main/doc/source/404.rst).

💡 **Solution**
It would be a neat feature being able to import previous file from the `ansys-sphinx-theme`:

```python
from ansys_sphinx_theme import ansys_404_template

...

notfound_template = ansys_404_template
```

**Comment by jorgepiloto** [comment]
I came up with this requirement after addressing https://github.com/pyansys/ansys-templates/issues/95

**Comment by RobPasMue** [comment]
We should avoid having duplicate implementations of 404 pages. From what I see, you already implemented it in the ansys-templates repository. I would avoid having to implement it in both places. If you decide to go on with the ansys-sphinx-templates implementation, please remove whatever is related to https://github.com/pyansys/ansys-templates/pull/102 in ansys-templates repo. Just to have a single source of 404 pages. Do you agree @jorgepiloto?

**Comment by jorgepiloto** [comment]
I agree @RobPasMue, just opened that as a temporary fix to this request.
