### ISSUE TITLE
Accessibility migration

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#95]
🐞 **Problem**
Our `ansys-sphinx-theme` is not compliant with [accessibility guidelines](), see:

- WAVE Report: https://wave.webaim.org/report#/https://sphinxdocs.ansys.com/

Notice that some of the features we use are inherited from the [pydata-sphinx-theme]. Thus, any accessibility improvements we make could be moved at some point to this other theme.

📝 **Solution**
After discussing privately, here is a list of the issues that need to be addressed for making our theme more accessible:

- [x] **Color related**
  - [x] Stop using Ansys gold and use near black
  - [x] Same applies for header links
  - [x] Hyperlinks must be vibrant blue

- [x] **Top navigation bar**
  - [x] Top navigation bar needs to reflect "normal", "active" and "hover" states
  - [x] Active navigation bar section needs to be underlined
  - [x] Navigation bar toggler dropdown must be visible in both light and dark theme

- [ ] **Left sidebar**
  - [x] Fix styling when hovering and for active section
  - [ ] Fix visibility when using a narrow browser

- [ ] **Right sidebar**
  - [x] Fix styling when hovering and for active section
  - [ ] Fix margin (this needs further discussion)
  - [ ] Fix titles

- [x] **Breadcrumbs**
  - [x] Remove bottom border

- [ ] **Body content**
  - [ ] Remove maximum width restriction on container
  - [ ] Impose auto margin

- [x] **Admonitions theme**
   - [x] Color for admonitions
![admonisions](https://user-images.githubusercontent.com/104772255/185375055-1bea4c2f-b7db-4bd8-aa34-c393473b30a6.PNG)

👥 **Teams**
This topic was originally raised by @timdansys and discussed with documentation and PyAnsys team. Pinging here all people related with this issue: @PipKat @MaxJPRey @RobPasMue @Revathyvenugopal162

🔗 **References**

Acesibility guidelines: https://www.w3.org/WAI/standards-guidelines/wcag/

[accesibility guidelines]: https://www.w3.org/WAI/standards-guidelines/wcag/
[pydata-sphinx-theme]: https://github.com/pydata/pydata-sphinx-theme

**Comment by jorgepiloto** [comment]
Linking here the pull requests which partially addressed this issue: #90 and #93.

**Comment by Revathyvenugopal162** [comment]
Marking the addressed problems in #90 and #93.

**Comment by RobM-official** [comment]
not me! I think you wanted @RobPasMue

**Comment by Revathyvenugopal162** [comment]
- [ ] Admonitions theme.
   - [ ] color for admonitions
![admonisions](https://user-images.githubusercontent.com/104772255/185375055-1bea4c2f-b7db-4bd8-aa34-c393473b30a6.PNG)

**Comment by RobPasMue** [comment]
Already created an issue on this last point: #100

**Comment by germa89** [comment]
I think #121 this is also relevant here...
