### ISSUE TITLE
Hover color makes text dissapear

### ISSUE THREAD

**Issue by akaszynski** [ansys/ansys-sphinx-theme#98]
I really like the recent changes with the CSS, but the hover color (for the side panel on the left) is white for the light theme, which makes text disappear when the cursor hovers over it.

For reference, here's the element:
```
<a class="reference internal" href="packaging.html">
   Packaging
  </a>
```

**Comment by RobPasMue** [comment]
Yep, I can confirm it. And not only on hover, but when selected it is not visible anymore. See example here:

![image](https://user-images.githubusercontent.com/37798125/184859637-9a07be66-6fa0-4481-a1b8-30af57709cc0.png)

**Comment by RobPasMue** [comment]
Pinging @Revathyvenugopal162 for resolution (if possible) - since she recently changed all these colors.
